collections:
  # Contains all Amazon Bedrock and DevOps Guru modules
  - name: https://github.com/ansible-collections/amazon.ai
    type: git
    version: main

  # Required for core AWS resource management (IAM, Lambda, S3)
  - name: amazon.aws
  
  # Required for auxiliary AWS services (SNS, SQS)
  - name: community.aws
