collections:
  # Contains all Amazon Bedrock and DevOps Guru modules
  - name: amazon.ai
  
  # Required for core AWS resource management (IAM, Lambda, S3)
  - name: amazon.aws
  
  # Required for auxiliary AWS services (SNS, SQS)
  - name: community.aws
